<?php

/**
 * @file
 * Installation file for UI Examples module.
 */

declare(strict_types=1);

/**
 * Add new permission to access the library to all roles.
 */
function ui_examples_update_8101(): void {
  if (\Drupal::moduleHandler()->moduleExists('user')) {
    $roles = \Drupal::entityTypeManager()->getStorage('user_role')
      ->loadMultiple();
    foreach (\array_keys($roles) as $rid) {
      \user_role_grant_permissions($rid, ['access_ui_examples_library']);
    }
  }
}
